### ISSUE TITLE
Logback core and classic are being included as a transitive dependency in all modules

### ISSUE THREAD

**Issue by tnovo** [feedzai/feedzai-openml#49]
There is a set of dependencies that are being included in all modules.

Since this aims to be a public API, I believe these dependencies should not be enforced (or even be transitive) to projects including this.

It's also a bad pratice to include dependencies in modules with packaging pom. 

I suggest moving the dependency section of the parent pom to the individual modules (where relevant) and setting logback-* dependencies as provided .

**Comment by pedrorijo91** [comment]
looks a valid concern. are you available to provide a PR? :)
